language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git valgrind
script:
  - make test
  - make clean
  - CFLAGS=-DTREE_PARENT_POINTERS make test
